# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tests.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tests(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(835, 620)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 260, 211, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Литература")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setText("Дикая Природа")
        self.pushButton_2.setGeometry(QtCore.QRect(280, 260, 231, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 260, 231, 91))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setText("История")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 370, 191, 171))
        self.label.setObjectName("label")
        pixmap5 = QtGui.QPixmap("literature.jpg")
        pixmap6 = pixmap5.scaled(256, 256)
        self.label.setPixmap(pixmap6)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 370, 191, 171))
        self.label_2.setObjectName("label_2")
        pixmap3 = QtGui.QPixmap("nature.jpg")
        pixmap4 = pixmap3.scaled(456, 456)
        self.label_2.setPixmap(pixmap4)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(580, 370, 191, 171))
        self.label_3.setObjectName("label_3")
        pixmap = QtGui.QPixmap("history.jpg")
        pixmap2 = pixmap.scaled(256, 256)
        self.label_3.setPixmap(pixmap2)
        self.pushButton.setFont(QtGui.QFont("Arial", 24))
        self.pushButton_3.setFont(QtGui.QFont("Arial", 24))
        self.pushButton_2.setFont(QtGui.QFont("Arial", 22))
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(310, 28, 191, 171))
        self.label_4.setObjectName("label_4")
        self.label_4.setText("Тесты")
        self.label_4.setFont(QtGui.QFont("Arial", 48))
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 10, 100, 50))
        self.pushButton_4.setObjectName("pushButton")
        self.pushButton_4.setText("Назад")
        self.pushButton_4.setFont(QtGui.QFont("Arial", 20))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))